---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: tikhonow/distrub:latest
        ports:
        - containerPort: 8000
        env:
        - name: hostDB
          value: "postgres-service" # Сервис базы данных
        - name: nameDB
          value: "test_dev_iot"
        - name: userDB
          value: "test"
        - name: passDB
          value: "testpassword"
        - name: logPath
          value: "./example.txt"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "test_dev_iot"
        - name: POSTGRES_USER
          value: "test"
        - name: POSTGRES_PASSWORD
          value: "testpassword"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
