# Generated by Django 5.1.3 on 2024-12-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='number',
            unique_together={('value', 'processed_at')},
        ),
    ]
